# Generated by Django 4.2.6 on 2023-12-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SHIRT', 'shirt'), ('PANTS', 'pants'), ('DRESS', 'dress'), ('SPORT_BRA', 'sport bra'), ('TIGHTS', 'tights'), ('SHOES', 'shoes')], max_length=50)),
                ('gender', models.CharField(choices=[('FEMALE', 'female'), ('MALE', 'male'), ('KIDS', 'kids')], default='OTHER', max_length=50)),
                ('season', models.CharField(choices=[('SUMMER', 'summer'), ('FALL', 'fall'), ('WINTER', 'winter'), ('SPRING', 'spring')], max_length=50)),
                ('collection', models.CharField(choices=[('SPORTSWEAR', 'sportswear'), ('EVENING', 'evening'), ('CASUAL', 'casual')], default='CASUAL', max_length=50)),
            ],
        ),
    ]
