# Generated by Django 4.2.6 on 2023-12-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('kids', 'kids')], default='OTHER', max_length=50),
        ),
    ]
