apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport-service
  namespace: my-namespace
spec:
  type: NodePort
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 30004
      targetPort: 8000  # Frontend port
---
apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport-service
  namespace: my-namespace
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 30005
      targetPort: 8080  # Backend port



# kubectl apply -f another-service.yaml
# echo "$(minikube ip) frontend.com" | tee -a C:\Users\AlphOmeg\Desktop\New folder\Koral\ingress-frontend.yaml  
# output : 192.168.49.2 frontend.com
