apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: my-namespace
spec:
  type: NodePort
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 30004 
      targetPort: 8000


# kubectl apply -f another-service.yaml
# minikube addons enable ingress
# kubectl apply -f ingress-frontend.yaml  
# echo "$(minikube ip) frontend.com" | tee -a C:\Users\AlphOmeg\Desktop\New folder\Koral\ingress-frontend.yaml  
# output : 192.168.49.2 frontend.com
