apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: ghcr.io/expruc/kubernetes-gradutaion-drill/k8s-final-drill:backend
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
