apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: my-namespace
spec:
  selector:
    app: frontend-app 
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

# kubectl apply -f frontend-service.yaml
