apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: ghcr.io/expruc/kubernetes-gradutaion-drill/k8s-final-drill:frontend
          ports:
            - containerPort: 8000
          env:
                - name: PORT
                  value: "8000" 
                - name: URLFORBACK
                  value: "http://backend-deployment.my-namespace.svc.cluster.local:8000"
