# Generated by Django 4.2.6 on 2023-10-25 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('event_status', models.CharField(choices=[('opened', 'opened'), ('closed', 'closed'), ('waiting for response', 'waiting for response'), ('waiting for treatment', 'waiting for treatment')], default='OPEN', max_length=100)),
                ('ability_open_a_draft', models.BooleanField(default=False)),
                ('ability_download_form_archive', models.BooleanField(default=False)),
                ('event_reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('shared_users', models.ManyToManyField(blank=True, related_name='shared_users', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='MessagesForm',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.form')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
            ],
            bases=('form.form',),
        ),
        migrations.CreateModel(
            name='FileSharingForm',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.form')),
                ('file_upload_date', models.DateField()),
                ('file', models.FileField(upload_to='')),
                ('upload_file_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            bases=('form.form',),
        ),
    ]
