# Generated by Django 4.2.6 on 2023-10-25 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesform',
            name='chat_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
        ),
    ]
