# Generated by Django 4.2.6 on 2023-10-25 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('id_number', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(111111111), django.core.validators.MaxValueValidator(999999999)])),
                ('email', models.EmailField(max_length=254)),
                ('unread_messages', models.ManyToManyField(blank=True, related_name='unread_messages', to='message.message')),
            ],
        ),
    ]
