# Generated by Django 4.2.6 on 2023-10-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_user_to_send_alter_message_chat_pointer_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unread_messages',
            field=models.ManyToManyField(blank=True, editable=False, related_name='unread_messages', to='message.message'),
        ),
    ]
