# Generated by Django 4.2.6 on 2023-12-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('status', models.CharField(choices=[('OUT_OF_STOCK', 'out of stock'), ('NOT_AVAILABLE', 'not available'), ('IN_STOCK', 'in stock')], default='IN_STOCK', max_length=80)),
                ('picture', models.ImageField(upload_to='')),
                ('category', models.ManyToManyField(related_name='category', to='category.category')),
            ],
        ),
    ]
