# Generated by Django 4.2.6 on 2023-12-19 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_alter_basket_total_price'),
        ('product', '0002_productinbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='basket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='basket.basket'),
            preserve_default=False,
        ),
    ]
