# Generated by Django 4.2.6 on 2023-12-19 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productinbasket_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInBasket',
        ),
    ]
