# Generated by Django 4.2.6 on 2023-10-19 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id_number', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(111111111), django.core.validators.MaxValueValidator(999999999)])),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
