# Generated by Django 4.2.6 on 2023-10-22 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.person')),
                ('work_place', models.CharField(max_length=100)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='people.person')),
            ],
            bases=('people.person',),
        ),
    ]
