# Generated by Django 4.2.6 on 2023-10-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_person_id_number_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
