# Generated by Django 4.2.6 on 2023-12-12 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('products', models.ManyToManyField(related_name='products', to='product.product')),
                ('shopping_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basket.basket')),
            ],
        ),
    ]
