# Generated by Django 4.2.6 on 2023-12-13 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_initial'),
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(editable=False, related_name='products', to='product.product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shopping_history',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='basket.basket'),
        ),
    ]
