# Generated by Django 4.2.6 on 2023-12-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_products_alter_user_shopping_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='products',
        ),
    ]
