# Generated by Django 4.2.6 on 2023-12-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_remove_basket_total_price'),
        ('user', '0003_remove_user_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shopping_history',
        ),
        migrations.AddField(
            model_name='user',
            name='shopping_history',
            field=models.ManyToManyField(related_name='shoppers', to='basket.basket'),
        ),
    ]
