# Generated by Django 4.2.6 on 2023-12-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_remove_basket_total_price'),
        ('user', '0004_remove_user_shopping_history_user_shopping_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shopping_history',
            field=models.ManyToManyField(editable=False, related_name='shoppers', to='basket.basket'),
        ),
    ]
