# Generated by Django 4.2.6 on 2023-10-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('pages_count', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('date_of_published', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('review_description', models.CharField(max_length=200)),
            ],
        ),
    ]
