# Generated by Django 4.2.6 on 2023-10-25 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('text', models.TextField(max_length=1000)),
                ('sending_date', models.DateField()),
                ('is_read', models.BooleanField(default=False)),
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_pointer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
            ],
        ),
    ]
