# Generated by Django 4.2.6 on 2023-10-25 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('chat', '0001_initial'),
        ('message', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_to_send',
            field=models.ManyToManyField(related_name='user_to_send', to='users.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_pointer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
