# Generated by Django 4.2.6 on 2023-12-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('basket_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_products', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('products', models.ManyToManyField(related_name='productsList', to='product.product')),
            ],
        ),
    ]
