# Generated by Django 4.2.6 on 2023-12-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_rename_products_basket_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=1000, null=True),
        ),
    ]
