# Generated by Django 4.2.6 on 2023-12-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_alter_basket_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='total_price',
        ),
    ]
