# Generated by Django 4.2.6 on 2023-12-19 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_alter_basket_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='number_of_products',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
