# Generated by Django 4.2.6 on 2024-01-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('salary', models.IntegerField()),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('other', 'other')], default=('female', 'female'), max_length=60)),
            ],
        ),
    ]
