# Generated by Django 4.2.6 on 2024-01-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_worker_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
