# Generated by Django 4.2.6 on 2024-01-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0003_delete_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteWorker',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('salary', models.IntegerField()),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('other', 'other')], default=('female', 'female'), max_length=60)),
            ],
            options={
                'db_table': 'Worker',
            },
        ),
    ]
